// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD35UINHWvE6YBTZIzoLQsTkmnBZSwycFs',
    appId: '1:820789529612:web:aa11630688f05f34813229',
    messagingSenderId: '820789529612',
    projectId: 'student-management-syste-ce0e9',
    authDomain: 'student-management-syste-ce0e9.firebaseapp.com',
    storageBucket: 'student-management-syste-ce0e9.appspot.com',
    measurementId: 'G-EB0PMGD91T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7gbA9BeVYehHcECICuCx60OhtyqEknMA',
    appId: '1:820789529612:android:c63de5bc8afe398e813229',
    messagingSenderId: '820789529612',
    projectId: 'student-management-syste-ce0e9',
    storageBucket: 'student-management-syste-ce0e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-D1Bg1L8JCCQYjHhE3unWxRyK3qXcedM',
    appId: '1:820789529612:ios:bf677fed4965b340813229',
    messagingSenderId: '820789529612',
    projectId: 'student-management-syste-ce0e9',
    storageBucket: 'student-management-syste-ce0e9.appspot.com',
    iosBundleId: 'com.example.studentManagementSystem',
  );
}
